### ISSUE TITLE
Create VistaNLP theory for curated training annotations

### ISSUE THREAD

**Issue by berquist** [isi-vista/curated-training-annotator#32]
In curated training, annotation for the absence of event triggers happens at the sentence level. For a specific event type of interest (such as `Conflict.Attack`), a search word of interest as an event trigger (such as `bomb`), and a sentence in a document that contains the word, the choice of whether or not that word is an event trigger is marked as true/false on the whole sentence. This means it is sufficient to have a boolean mask for which sentences are annotated, and those that are not are the negative examples.

Create a `CuratedTrainingAnnotationTheory` that maps each sentence to one or more `CuratedTrainingAnnotation`s, where each annotation is a collection of event components from https://github.com/isi-vista/vistanlp-sandbox/blob/master/vistanlp_sandbox/models/events.py.

We might want to inherit from [`SpanSortedListTheory`](https://github.com/isi-nlp/isi-flexnlp/blob/master/flexnlp/model/span.py) rather than from [`SentenceTheory`](https://github.com/isi-nlp/isi-flexnlp/blob/master/flexnlp/model/sentence.py) directly.

**Comment by rgabbard** [comment]
> This means it is sufficient to have a boolean mask for which sentences are annotated, and those that are not are the negative examples.

To clarify here, sentences which are not annotated are not training data at all.  Sentences which are annotated but do not contain an `EventText` are negative examples. Sentences which are annotated and do contain an `EventText` are positive examples.

Note we also need one `CuratedTrainingTheory` per event type.  Alternately, it might be cleaner to have one `CuratedTrainingTheory` which stores a `ImmutableSetMultiDict`  from event types to annotated sentences.

Rather than storing event components, maybe we should just store an `EventMentionTheory`?

**Comment by berquist** [comment]
Closing this per https://github.com/isi-vista/gaia-event-extraction/pull/48
