### ISSUE TITLE
Timestamped annotations

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/curated-training-annotator#8]
Are annotations marked with the time when they were created?  If not, what would we need to add to support this?

**Comment by Rentier** [comment]
When do you need this information? At annotation time or during offline evaluation?

**Comment by rgabbard** [comment]
During offline evaluation - the idea here is to allow us to make time-based (rather than # of annotation-based) learning curves in order to allow time efficiency comparisons between incomparable annotation approaches.

**Comment by Rentier** [comment]
I think that we already log that, i.e.. in the `SpanCreatedEvent` of webanno. We also log the deletion. Events typically have timestamps saved.

**Comment by reckart** [comment]
We are working on a learning curve to be shown in the UI (https://github.com/inception-project/inception/issues/649) - for it, we use the `RecommenderEvaluationResultEvent`. Currently, we look at the last *n* events in order to draw the curves, but you could also to a time-based approach since the events are logged with a timestamp. Whether this event is suitable for you or not depends in whether or not you make use of the *recommender* framework in INCEpTION.

**Comment by rgabbard** [comment]
Annotations are stored with timestamps in the DB:

```
| 278 | SpanCreatedEvent               | 2019-03-26 12:27:32 | admin             | {"addr":7382,"begin":269,"end":276,"type":"webanno.custom.CTEventSpan","text":"disease"}                                                                                                       |       2 |        5 | admin             |
```

from 

`SELECT * FROM logged_event ORDER BY created`
